In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
ls

AutoInsurance.csv                        AutoInsurance.xls
AutoInsurance_PolynomialRegression.py    AutoInsurSweden_DataSet1.pdf
AutoInsurance.py                         Auto.py
AutoInsurance_SimpleLinearRegression.py  Untitled.ipynb
AutoInsurance_SVR.py


In [93]:
data = pd.read_csv('AutoInsurance.csv')
data.head()

X      Y
0  108  392.5
1   19   46.2
2   13   15.7
3  124  422.2
4   40  119.4

In [192]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
y = y.reshape(X.shape[0],1)

X = np.append(np.ones((X.shape[0],1)),X,axis = 1)
y.shape

(63, 1)

In [193]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
print(x_train.shape)

(50, 2)


In [194]:
def cost_func(X,y,theta):
    m = X.shape[0]
    z = np.dot(X,theta)
    J = (0.5/m)*np.sum(np.power(z-y,2))
    return J


In [223]:
#intialising parameters
init_theta = np.random.rand(2,1)
init_theta

array([[ 0.12428423],
       [ 0.93712938]])

In [224]:
cost = cost_func(x_train,y_train,init_theta)
cost

4733.5117907304821

In [225]:
def find_grads(theta,X,y):
    m = X.shape[0]
    #print(str(X.shape)+" hehe "+str(theta.shape))
    grad0 = (1/m)*np.sum(np.dot(X,theta)-y)
    grad1 = (1/m)*np.sum(np.multiply(np.dot(X,theta)-y,X[:,1]))
    
    #grads = (1/m)*np.sum(np.dot(np.dot(X,theta)-y,X))
        
    #grads["grad0"] = grad0
    #grads["grad1"] = grad1
    return grad0,grad1


''''grad0,grad1 = find_grads(theta,X,y)
        #grad0 = grads["grad0"]
        #grad1 = grads["grad1"]
        theta0 = theta0 - alpha*grad0
        theta1 = theta1 - alpha*grad1
        #theta = theta - alpha*grads
        theta[0,0] = theta0
        theta[1,0] = theta1''''

SyntaxError: EOL while scanning string literal (<ipython-input-225-2511d8204f69>, line 21)

In [226]:
def gradient_descent(iterations,alpha,theta,X,y):
    m = X.shape[0]
    q = alpha*(1/m)*np.dot(X.T,np.dot(X,theta)-y)
    print(q.shape)
    
    for i in range(iterations):
        theta = theta - alpha*(1/m)*np.dot(X.T,np.dot(X,theta)-y)
        
    return theta


In [227]:
print(init_theta)
opt_theta = gradient_descent(100,0.01,init_theta,x_train,y_train)
print(opt_theta)

[[ 0.12428423]
 [ 0.93712938]]
(2, 1)
[[ -1.26292529e+85]
 [ -5.08496601e+86]]


In [228]:
cost = cost_func(x_train,y_train,opt_theta)
cost

1.071148245129401e+176

In [229]:
y_pred = np.dot(x_test,opt_theta)

In [230]:
y_pred

array([[ -1.01825613e+88],
       [ -2.28949763e+88],
       [ -1.11995545e+88],
       [ -2.03524933e+88],
       [ -2.89969355e+88],
       [ -1.47590307e+88],
       [ -4.58909866e+87],
       [ -6.30662078e+88],
       [ -1.27250443e+88],
       [ -2.04661566e+87],
       [ -1.02962246e+87],
       [ -8.14857487e+87],
       [ -1.17080511e+88]])